#!/bin/bash
#
# Yet Another GetOpt. pbrisbin 2011
#
###

__errorout() { # {{{
  local errno=$1; shift
  echo "error: $*" >&2; exit $errno
} # }}}

__invalid_option()   { __errorout 2 "invalid option $1"      ; }
__missing_option()   { __errorout 3 "option $1 is required"  ; }
__duplicate_option() { __errorout 4 "duplicate option $1 "   ; }
__missing_argument() { __errorout 5 "missing argument for $1"; }
__extra_argument()   { __errorout 6 "extra argument for $1"  ; }

__set_values() { # {{{
  local parse_info arg n

  local long_opt short_opt opt_message default nargs argument \
    variable required

  sopts_list=()
  lopts_list=()

  for arg in "${opts[@]}"; do
    [[ -z "$arg" ]] && continue

    IFS=',' read -a parse_info <<< "$arg"
    n="${#parse_info[@]}"

    [[ $n -lt 3 || $n -gt 7 ]] && __errorout 1 'invalid number of tokens in option definiton'

    # reread vars to trim whitespace
    read -r long_opt    <<< "${parse_info[0]}"
    read -r short_opt   <<< "${parse_info[1]}"
    read -r opt_message <<< "${parse_info[2]}"

    [[ $n -ge 4 ]] && read -r default  <<< "${parse_info[3]}" || default=false
    [[ $n -ge 5 ]] && read -r nargs    <<< "${parse_info[4]}" || nargs=0
    [[ $n -ge 6 ]] && read -r argument <<< "${parse_info[5]}" || argument='<ARG>'
    [[ $n -ge 7 ]] && read -r variable <<< "${parse_info[6]}" || variable="$long_opt"

    [[ -n "$default" && "$default" != 'REQUIRED' ]] && required=false || required=true

    [[ "$nargs" != 'N' && -n "${nargs//[0-9]/}" ]] && __errorout 1 "invalid number of arguments, token was \`$nargs'"

    # add to a list of keys
    sopts_list[$short_opt]="$long_opt"
    lopts_list[$long_opt]="$short_opt"

    # create an "extension table" of parameters, last field is "seen"
    eval "$long_opt=( \"$short_opt\" \"$opt_message\" \"$default\" \"$nargs\" \"$argument\" \"$variable\" $required false)"

    # clear variables for next option
    unset long_opt short_opt opt_message default nargs argument variable \
      required
  done
} # }}}

__help_message() { # {{{
  local long_opt short_opt opt_message nargs argument required \
    lb rb sopt usage options_list

  # TODO it appears associative arrays are stored in the reverse order
  # they're declared. this may not be true, but i rely on it it to print
  # the help in the order it was defined
  for long_opt in ${!lopts_list[@]}; do
    eval "short_opt=\${$long_opt[0]}"
    eval "opt_message=\${$long_opt[1]}"
    eval "nargs=\${$long_opt[3]}"
    eval "argument=\${$long_opt[4]}"
    eval "required=\${$long_opt[6]}"

    $required || { lb='[ '; rb=' ]'; }

    case "$nargs" in # compare as string
      '0') sopt="$lb-$short_opt$rb"              ; argument=''              ;;
      '1') sopt="$lb-$short_opt $argument$rb"                               ;;
      *)   sopt="$lb-$short_opt $argument ...$rb"; argument="$argument ..." ;;
    esac

    usage="$sopt $usage"
    options_list=( "$(printf "    %-25.25s %s" "-$short_opt, --$long_opt $argument" "$opt_message")" "${options_list[@]}" )

    unset short_opt opt_message nargs argument required lb rb sopt lopt
  done

  echo "usage: $progname $usage"     >&2
  printf "%s\n" "${options_list[@]}" >&2
  exit 1
} # }}}

__setup_short_opt() { # {{{
  sopt="${1/-/}"
  lopt="${sopts_list[$sopt]}"

  [[ -z "$lopt" ]]    && __invalid_option "-$sopt"
  eval "\${$lopt[7]}" && __duplicate_option "-$sopt"
} # }}}

__setup_long_opt() { # {{{
  lopt="${1/--/}"
  sopt="${lopts_list[$lopt]}"

  [[ -z "$sopt" ]]    && __invalid_option "--$lopt"
  eval "\${$lopt[7]}" && __duplicate_option "--$lopt"
} # }}}

__consume_args() { # {{{
  local nexpd="$1" nseen=0; shift

  while [[ -n "$1" ]] && [[ ! "$1" =~ -.* ]]; do
    nseen=$((nseen+1))
    [[ "$nexpd" != 'N' && $nseen -gt $nexpd ]] && __extra_argument "--$lopt"

    optargs+=( "$1" ); shift
  done

  [[ "$nexpd" != 'N' && $nseen -ne $nexpd ]] && __missing_argument "--$lopt"
  [[ "$nexpd" == 'N' && $nseen -eq 0      ]] && __missing_argument "--$lopt"

  return $nseen
} # }}}

__set_unseen_args() { # {{{
  local lopt required seen default nargs

  for lopt in "${!lopts_list[@]}"; do
    eval "default=\${$lopt[2]}"
    eval "nargs=\${$lopt[3]}"
    eval "required=\${$lopt[6]}"
    eval "seen=\${$lopt[7]}"

    $seen     && continue
    $required && __missing_option "--$lopt"

    case "$nargs" in
      0) eval "$lopt=$default"     ;;
      *) eval "$lopt=( $default )" ;;
    esac
  done
} # }}}

yago_parse() {
  progname="$1"; shift

  # read options definition from stdin
  while IFS=$'\n' read -r line; do
    [[ -n "$line" ]] && opts+=( "$line" )
  done

  # set two key value arrays which map valid long to short options and
  # valid short to long options (to make lookups either way convenient) as
  # well as an array named for each long option which holds all of the
  # information about it: short opt, message, default, required, etc.
  __set_values

  while [[ -n "$1" ]]; do
    case "$1" in
      -h|--help) __help_message         ;;
      --)        shift; break           ;;
      --*)       __setup_long_opt  "$1" ;;
      -*)        __setup_short_opt "$1" ;;
      *)         break ;; # unconsumed arg
    esac
    shift

    eval "nargs=\${$lopt[3]}"

    if [[ "$nargs" != 'N' && $nargs -eq 0 ]]; then
      eval "$lopt=true"
    else
      # fill optargs and return the number of arguments which were
      # consumed by the process. error on too few or too many
      __consume_args "$nargs" "$@" || shift $?
      eval "$lopt=( $(printf '"%s" ' "${optargs[@]}"))"
    fi

    # note that you've seen this option
    declare $lopt[7]=true

    unset nargs ret lopt sopt
    optargs=()
  done

  # any leftover args get placed in an args array
  [[ "$#" -ne 0 ]] && eval "args=( $(printf '"%s" ' "$@"))"

  # roll through any options we haven't seen yet. if they're required
  # throw an error, otherwise set them to the default value
  __set_unseen_args

  # unset the variables we've used as to not pollute the caller
  unset progname opts optargs sopts_list lopts_list

  return 0;
}

declare -a opts
declare -a optargs
declare -A sopts_list
declare -A lopts_list
